---
#Название PB
- name: Сбор Камер на vlan10 Juniper
#На какие hosts будем его применять  
  hosts: Juniper-EX4200
#Подключаем необходимый модуль
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no
#Объявим переменную для определения настроек подключения
  vars:
    provider_info:
      host: "{{ inventory_hostname }}"
      username: "r_ryabcev" 
      password: "AB9jWS95"
      port: "22"
#Прописываем наши задачки
  tasks:
#Проверка доступности Juniper
   - name: Juniper проверка подключения 
     wait_for:
      host: "{{ inventory_hostname }}"
      port: "22"
      timeout: 10
#Сбор данных на vlan10 Juniper
   - name: Получение информации на кпортах Juniper
     juniper_junos_command:
      provider: "{{ provider_info }}"
      commands: 
      - "show arp interface vlan.10"
      dest: "/etc/ansible/JunCameraISVN/{{ group_names }}.{{ inventory_hostname }}.txt"
      format: text
